vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO foonathan/cppast
  REF f00df6675d87c6983033d270728c57a55cd3db22
  SHA512 7d045fdbb9b7473f0b082ebb289560111542fa82e7317f8e651d921bd146f30a408725bcab7f4f9079c7bda254a6014c385614b7a6dc22f92ab379508153d53a
  HEAD_REF main
  PATCHES
    0001-fixup-top-level-directory.patch
    0002-fixup-tiny-process-library.patch
)

vcpkg_check_linkage(
  ONLY_STATIC_LIBRARY
)

if (LLVM_CONFIG_BINARY)
  list(APPEND CPPAST_ADDITIONAL_OPTIONS -DLLVM_CONFIG_BINARY=${LLVM_CONFIG_BINARY})
endif()

if (LIBCLANG_LIBRARY)
  list(APPEND CPPAST_ADDITIONAL_OPTIONS -DLIBCLANG_LIBRARY=${LIBCLANG_LIBRARY})
endif()

if (LIBCLANG_INCLUDE_DIR)
  list(APPEND CPPAST_ADDITIONAL_OPTIONS -DLIBCLANG_INCLUDE_DIR=${LIBCLANG_INCLUDE_DIR})
endif()

if (CLANG_BINARY)
  list(APPEND CPPAST_ADDITIONAL_OPTIONS -DCLANG_BINARY=${CLANG_BINARY})
endif()

message(STATUS ${CPPAST_ADDITIONAL_OPTIONS})

vcpkg_cmake_configure(
  SOURCE_PATH ${SOURCE_PATH}
  OPTIONS
    -DBUILD_SHARED_LIBS=OFF
    -DCPPAST_BUILD_TEST=OFF
    -DCPPAST_BUILD_EXAMPLE=OFF
    -DCPPAST_BUILD_TOOL=OFF
    ${CPPAST_ADDITIONAL_OPTIONS}
)

vcpkg_cmake_install()

file(
  REMOVE_RECURSE
  ${CURRENT_PACKAGES_DIR}/debug/include
)

configure_file(
  "${CMAKE_CURRENT_LIST_DIR}/config.cmake.in"
  "${CURRENT_PACKAGES_DIR}/share/foonathan-cppast/foonathan-cppast-config.cmake"
  @ONLY
)

vcpkg_install_copyright(
  FILE_LIST ${SOURCE_PATH}/LICENSE.md
)